- name: Standard configuration
  hosts: azril-vm
  become: true
  roles:
    - common

- name: Setup Docker
  hosts: azril-vm
  become: true
  roles:
    - docker-setup

- name: Add User to Group Docker
  hosts: azril-vm
  become: true
  roles:
    - users
