- name: Install Docker Module for Python
  pip:
   name: docker

- name: Add Group Docker
  ansible.builtin.group:
    name: docker
    state: present

- name: Add User to Docker Group
  ansible.builtin.user:
    name: manage
    groups: docker
    append: yes
